// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vijeoGAPI.Data;

#nullable disable

namespace vijeoGAPI.Migrations
{
    [DbContext(typeof(VideoGameDBContext))]
    [Migration("20251115122203_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vijeoGAPI.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Santa Monica Studio",
                            Platform = "PlayStation 4",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Rockstar Studios",
                            Platform = "PS 4",
                            Publisher = "Rockstar Games",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "343 Industries",
                            Platform = "Xbox Series X",
                            Publisher = "Xbox Game Studios",
                            Title = "Halo Infinite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
